#version 430

layout (local_size_x = 1, local_size_y = 1) in;
layout (rgba32f, binding = 0) uniform image2D img_out;

uniform float time;

void main() {
    ivec2 idx = ivec2(int(gl_GlobalInvocationID.x), int(gl_GlobalInvocationID.y));
    ivec2 image_size = ivec2(int(gl_NumWorkGroups.x), int(gl_NumWorkGroups.y));
    float r = float(idx.x) / float(image_size.x);
    float g = float(idx.y) / float(image_size.y);
    vec4 color = vec4(r, g, time, 1.0f);
    imageStore(img_out, idx, color);
}